### ISSUE TITLE
Cool project. Method for getting older versions?

### ISSUE THREAD

**Issue by commadelimited** [tgvashworth/cdnjs#1]
I was just on cdnjs today and noticed they maintain historical versions. Does your code have a means by which to retrieve older versions of libraries?

**Comment by tgvashworth** [comment]
Thanks! Not at the mo (this was a very quick hack) but I could definitely add it.

**Comment by commadelimited** [comment]
Roger. Just checking.

**Comment by tgvashworth** [comment]
@commadelimited Hey Andy – I've now added this, check it out:

```
$ cdnjs url jquery@1.7.1
jquery@1.7.1                  : //cdnjs.cloudflare.com/ajax/libs/jquery/1.7.1/jquery.min.js
```
