### ISSUE TITLE
Update version on npmjs.org

### ISSUE THREAD

**Issue by gavinhungry** [tgvashworth/cdnjs#13]
You've fixed some issues that I had with 0.2.1 (notably splitting the CLI out), can you tag a new release and publish to npmjs.org?

**Comment by nickserv** [comment]
It seems like this has been fixed in `v0.3.0`, which has been released (it's not the latest version, but the fix should still be there).

**Comment by tgvashworth** [comment]
Thanks for pinging me on this, sorry I didn't actually respond about it!

Latest is `0.3.2` which is published.
